'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Wallet, Plus, Edit, Trash2, QrCode, CheckCircle, XCircle, Info, RefreshCw, AlertCircle } from 'lucide-react';
import toast from 'react-hot-toast';
import Image from 'next/image';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { SUPPORTED_CRYPTOS } from '@/lib/wallet-config';

interface CryptoWallet {
  id: string;
  currency: string;
  walletAddress: string;
  qrCodeUrl: string | null;
  network: string | null;
  minDepositUsdt: number;
  minWithdrawUsdt: number;
  isEnabled: boolean;
  isConfigured?: boolean; // Computed: true if wallet address is set
}

export function CryptoWalletsTab() {
  const [wallets, setWallets] = useState<CryptoWallet[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingWallet, setEditingWallet] = useState<CryptoWallet | null>(null);
  const [autoGeneratedQR, setAutoGeneratedQR] = useState<string | null>(null);
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [walletToDelete, setWalletToDelete] = useState<{ id: string, currency?: string } | null>(null);

  const [formData, setFormData] = useState({
    currency: '',
    walletAddress: '',
    network: '',
    minDepositUsdt: '10',
    minWithdrawUsdt: '10',
    isEnabled: false,
  });

  useEffect(() => {
    fetchWallets();
  }, []);

  const getAuthHeaders = () => {
    // Token automatically sent via httpOnly cookie
    return {
    };
  };

  const fetchWallets = async () => {
    try {
      const response = await fetch('/api/admin/crypto-wallets', {
        headers: getAuthHeaders(),
      });
      if (response.ok) {
        const data = await response.json();
        // Add isConfigured flag
        const walletsWithConfig = data.map((wallet: CryptoWallet) => ({
          ...wallet,
          isConfigured: wallet.walletAddress && wallet.walletAddress.length > 0,
        }));
        setWallets(walletsWithConfig);
      }
    } catch (error) {
      console.error('Error fetching wallets:', error);
      toast.error('Failed to fetch wallets');
    } finally {
      setIsLoading(false);
    }
  };

  // Auto-generate QR code when wallet address changes
  useEffect(() => {
    if (formData.walletAddress && formData.walletAddress.length > 10) {
      const qrUrl = getQRCodeURL(formData.walletAddress);
      setAutoGeneratedQR(qrUrl);
    } else {
      setAutoGeneratedQR(null);
    }
  }, [formData.walletAddress]);

  const getQRCodeURL = (address: string) => {
    return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(address)}`;
  };

  const handleOpenDialog = (wallet?: CryptoWallet) => {
    if (wallet) {
      setEditingWallet(wallet);
      setFormData({
        currency: wallet.currency,
        walletAddress: wallet.walletAddress,
        network: wallet.network || '',
        minDepositUsdt: wallet.minDepositUsdt.toString(),
        minWithdrawUsdt: wallet.minWithdrawUsdt.toString(),
        isEnabled: wallet.isEnabled,
      });
      setAutoGeneratedQR(getQRCodeURL(wallet.walletAddress));
    } else {
      setEditingWallet(null);
      setFormData({
        currency: '',
        walletAddress: '',
        network: '',
        minDepositUsdt: '10',
        minWithdrawUsdt: '10',
        isEnabled: false,
      });
      setAutoGeneratedQR(null);
    }
    setIsDialogOpen(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.currency) {
      toast.error('Currency is required');
      return;
    }

    // Wallet address is required only if enabling the wallet
    if (formData.isEnabled && !formData.walletAddress) {
      toast.error('Wallet address is required to enable this crypto');
      return;
    }

    const data = {
      currency: formData.currency.toUpperCase(),
      walletAddress: formData.walletAddress,
      network: formData.network,
      minDepositUsdt: parseFloat(formData.minDepositUsdt),
      minWithdrawUsdt: parseFloat(formData.minWithdrawUsdt),
      isEnabled: formData.isEnabled,
      ...(editingWallet && { id: editingWallet.id }),
    };

    try {
      const url = '/api/admin/crypto-wallets';
      const method = editingWallet ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: {
          ...getAuthHeaders(),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (response.ok) {
        toast.success(editingWallet ? 'Wallet updated successfully' : 'Wallet created successfully');
        setIsDialogOpen(false);
        fetchWallets();
      } else {
        const error = await response.json();
        toast.error(error.error || 'Failed to save wallet');
      }
    } catch (error) {
      console.error('Error saving wallet:', error);
      toast.error('Failed to save wallet');
    }
  };

  const handleDelete = (id: string, currency?: string) => {
    setWalletToDelete({ id, currency });
    setDeleteConfirmOpen(true);
  };

  const confirmDelete = async () => {
    if (!walletToDelete) return;

    try {
      const response = await fetch(`/api/admin/crypto-wallets?id=${walletToDelete.id}`, {
        method: 'DELETE',
        headers: getAuthHeaders(),
      });

      if (response.ok) {
        toast.success(`${walletToDelete.currency || 'Wallet'} deleted successfully`);
        fetchWallets();
        setDeleteConfirmOpen(false);
        setWalletToDelete(null);
      } else {
        toast.error('Failed to delete wallet');
      }
    } catch (error) {
      console.error('Error deleting wallet:', error);
      toast.error('Failed to delete wallet');
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <Alert className="border-blue-500/50 bg-blue-500/10">
        <Info className="h-4 w-4" />
        <AlertDescription>
          <strong>QR codes are auto-generated!</strong> Just enter your wallet address and the QR code will be created automatically. No manual upload needed.
        </AlertDescription>
      </Alert>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Wallet className="h-5 w-5" />
                Crypto Wallets Management
              </CardTitle>
              <CardDescription className="mt-1">
                Configure wallet addresses for deposits. All supported cryptocurrencies are listed below.
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <Button
                onClick={() => handleOpenDialog()}
                size="sm"
                variant="default"
                className="gap-2"
              >
                <Plus className="h-4 w-4" />
                Add New Crypto
              </Button>
              <Button
                onClick={fetchWallets}
                size="sm"
                variant="outline"
                disabled={isLoading}
              >
                <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
              </Button>
            </div>
          </div>
        </CardHeader>

        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>
                {editingWallet ? 'Edit Crypto Wallet' : 'Add New Crypto Wallet'}
              </DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              {!editingWallet ? (
                <Alert className="border-green-500/50 bg-green-500/10">
                  <Info className="h-4 w-4" />
                  <AlertDescription className="text-sm">
                    <strong>Adding a new crypto:</strong> You can add a crypto entry without a wallet address (it will be disabled). Configure the wallet address later to enable it for deposits.
                  </AlertDescription>
                </Alert>
              ) : (
                <Alert className="border-blue-500/50 bg-blue-500/10">
                  <QrCode className="h-4 w-4" />
                  <AlertDescription className="text-sm">
                    QR codes are generated automatically from your wallet address. No need to upload anything!
                  </AlertDescription>
                </Alert>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="currency">
                    Currency Symbol <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="currency"
                    placeholder="e.g., BTC, ETH, USDT"
                    value={formData.currency}
                    onChange={(e) => setFormData({ ...formData, currency: e.target.value.toUpperCase() })}
                    required
                    disabled={!!editingWallet}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="network">
                    Network <span className="text-muted-foreground text-xs">(optional)</span>
                  </Label>
                  <Input
                    id="network"
                    placeholder="e.g., TRC20, ERC20, BEP20 (optional)"
                    value={formData.network}
                    onChange={(e) => setFormData({ ...formData, network: e.target.value })}
                  />
                  <p className="text-xs text-muted-foreground">
                    Leave blank if this cryptocurrency doesn't use a specific network
                  </p>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="walletAddress">
                  Wallet Address {formData.isEnabled && <span className="text-red-500">*</span>}
                </Label>
                <Input
                  id="walletAddress"
                  placeholder="Your receiving wallet address"
                  value={formData.walletAddress}
                  onChange={(e) => setFormData({ ...formData, walletAddress: e.target.value })}
                  required={formData.isEnabled}
                />
                <p className="text-xs text-muted-foreground">
                  {formData.isEnabled
                    ? 'QR code will be generated automatically from this address'
                    : 'Wallet address is required to enable this cryptocurrency'}
                </p>
              </div>

              {/* QR Code Preview */}
              {autoGeneratedQR && (
                <div className="space-y-2">
                  <Label>Auto-Generated QR Code Preview</Label>
                  <div className="flex items-center gap-4 p-4 bg-muted/50 rounded-lg">
                    <div className="relative w-32 h-32 bg-white p-2 rounded-lg border-2">
                      <Image
                        src={autoGeneratedQR}
                        alt="QR Code Preview"
                        fill
                        className="object-contain p-1"
                        unoptimized
                      />
                    </div>
                    <div className="flex-1">
                      <p className="text-sm font-medium mb-1">✅ QR code ready!</p>
                      <p className="text-xs text-muted-foreground">
                        This QR code will be shown to users when they deposit {formData.currency || 'this crypto'}.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="minDepositUsdt">
                    Minimum Deposit (USDT)
                  </Label>
                  <Input
                    id="minDepositUsdt"
                    type="number"
                    step="any"
                    min="0"
                    placeholder={`e.g., ${formData.currency === 'BTC' ? '0.001' : formData.currency === 'ETH' ? '0.01' : '10'}`}
                    value={formData.minDepositUsdt}
                    onChange={(e) => setFormData({ ...formData, minDepositUsdt: e.target.value })}
                  />
                  <p className="text-xs text-muted-foreground">
                    Enter the minimum deposit amount in USDT
                  </p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="minWithdrawUsdt">
                    Minimum Withdraw (USDT)
                  </Label>
                  <Input
                    id="minWithdrawUsdt"
                    type="number"
                    step="any"
                    min="0"
                    placeholder={`e.g., ${formData.currency === 'BTC' ? '0.001' : formData.currency === 'ETH' ? '0.01' : '10'}`}
                    value={formData.minWithdrawUsdt}
                    onChange={(e) => setFormData({ ...formData, minWithdrawUsdt: e.target.value })}
                  />
                  <p className="text-xs text-muted-foreground">
                    Enter the minimum withdraw amount in USDT
                  </p>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <Switch
                  id="isEnabled"
                  checked={formData.isEnabled}
                  onCheckedChange={(checked) => setFormData({ ...formData, isEnabled: checked })}
                />
                <Label htmlFor="isEnabled" className="cursor-pointer">
                  Enable this wallet for deposits
                </Label>
              </div>

              <DialogFooter>
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit">
                  {editingWallet ? 'Update Wallet' : 'Create Wallet'}
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>

        <CardContent>
          {wallets.length === 0 ? (
            <div className="text-center py-12">
              <Wallet className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
              <p className="text-muted-foreground mb-4">Loading cryptocurrencies...</p>
            </div>
          ) : (
            <div className="grid gap-4">
              {wallets.map((wallet) => {
                const cryptoConfig = SUPPORTED_CRYPTOS[wallet.currency];
                return (
                  <Card key={wallet.id} className="overflow-hidden">
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex items-start gap-4 flex-1">
                          {/* Crypto Logo */}
                          <div className="relative w-16 h-16 rounded-lg border-2 shrink-0 bg-gradient-to-br from-blue-500/10 to-purple-500/10 p-2">
                            {cryptoConfig?.logoUrl ? (
                              <Image
                                src={cryptoConfig.logoUrl}
                                alt={`${wallet.currency} Logo`}
                                fill
                                className="object-contain p-1"
                                unoptimized
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center text-2xl font-bold">
                                {wallet.currency[0]}
                              </div>
                            )}
                          </div>

                          {/* Wallet Info */}
                          <div className="flex-1 space-y-2">
                            <div className="flex items-center gap-2 flex-wrap">
                              <h3 className="text-lg font-bold">{wallet.currency}</h3>
                              <span className="text-sm text-muted-foreground">
                                {cryptoConfig?.name || wallet.currency}
                              </span>

                              {/* Configuration Status */}
                              {wallet.isConfigured ? (
                                <Badge variant="default" className="bg-green-500">
                                  <CheckCircle className="h-3 w-3 mr-1" />
                                  Configured
                                </Badge>
                              ) : (
                                <Badge variant="secondary" className="bg-orange-500/20 text-orange-600">
                                  <AlertCircle className="h-3 w-3 mr-1" />
                                  Not Configured
                                </Badge>
                              )}

                              {/* Enable/Disable Status */}
                              {wallet.isConfigured && (
                                <Badge variant={wallet.isEnabled ? 'default' : 'secondary'}>
                                  {wallet.isEnabled ? (
                                    <>
                                      <CheckCircle className="h-3 w-3 mr-1" />
                                      Enabled
                                    </>
                                  ) : (
                                    <>
                                      <XCircle className="h-3 w-3 mr-1" />
                                      Disabled
                                    </>
                                  )}
                                </Badge>
                              )}

                              {wallet.network && (
                                <Badge variant="outline">{wallet.network}</Badge>
                              )}
                            </div>

                            <div className="space-y-1">
                              {wallet.isConfigured ? (
                                <>
                                  <div className="flex items-center gap-2">
                                    <span className="text-sm text-muted-foreground">Address:</span>
                                    <code className="text-xs font-mono bg-muted px-2 py-1 rounded">
                                      {wallet.walletAddress.slice(0, 16)}...{wallet.walletAddress.slice(-8)}
                                    </code>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className="text-sm text-muted-foreground">Min Deposit:</span>
                                    <span className="text-sm font-medium">{wallet.minDepositUsdt} USDT</span>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className="text-sm text-muted-foreground">Min Withdraw:</span>
                                    <span className="text-sm font-medium">{wallet.minWithdrawUsdt} USDT</span>
                                  </div>
                                </>
                              ) : (
                                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                  <AlertCircle className="h-4 w-4" />
                                  <span>Click edit to configure wallet address</span>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>

                        {/* Actions */}
                        <div className="flex items-center gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleOpenDialog(wallet)}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() => handleDelete(wallet.id, wallet.currency)}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      <AlertDialog open={deleteConfirmOpen} onOpenChange={setDeleteConfirmOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Cryptocurrency?</AlertDialogTitle>
            <AlertDialogDescription>
              {walletToDelete?.currency
                ? `Are you sure you want to delete ${walletToDelete.currency}? This action cannot be undone.`
                : 'Are you sure you want to delete this wallet? This action cannot be undone.'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete} className="bg-red-600 hover:bg-red-700 text-white">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
